export const VIEW_SITE_LIST_REQUEST = 'VIEW_SITE_LIST_REQUEST';
export const VIEW_SITE_LIST_SUCCESS = 'VIEW_SITE_LIST_SUCCESS';
export const VIEW_SITE_LIST_FAILURE = 'VIEW_SITE_LIST_FAILURE';
export const VIEW_SITE_LIST_RESET = 'VIEW_SITE_LIST_RESET';

export const UPDATE_SITE_REQUEST = 'UPDATE_SITE_REQUEST';
export const UPDATE_SITE_SUCCESS = 'UPDATE_SITE_SUCCESS';
export const UPDATE_SITE_FAILURE = 'UPDATE_SITE_FAILURE';
export const UPDATE_SITE_RESET = 'UPDATE_SITE_RESET';

export const DELETE_SITE_REQUEST = 'DELETE_SITE_REQUEST';
export const DELETE_SITE_SUCCESS = 'DELETE_SITE_SUCCESS';
export const DELETE_SITE_FAILURE = 'DELETE_SITE_FAILURE';
export const DELETE_SITE_RESET = 'DELETE_SITE_RESET';

export const VIEW_SINGLE_SITE_REQUEST = 'VIEW_SINGLE_SITE_REQUEST';
export const VIEW_SINGLE_SITE_SUCCESS = 'VIEW_SINGLE_SITE_SUCCESS';
export const VIEW_SINGLE_SITE_FAILURE = 'VIEW_SINGLE_SITE_FAILURE';
export const VIEW_SINGLE_SITE_RESET = 'VIEW_SINGLE_SITE_RESET';

export const GET_RANDOM_SITE_REQUEST = 'GET_RANDOM_SITE_REQUEST';
export const GET_RANDOM_SITE_SUCCESS = 'GET_RANDOM_SITE_SUCCESS';
export const GET_RANDOM_SITE_FAILURE = 'GET_RANDOM_SITE_FAILURE';
export const GET_RANDOM_SITE_RESET = 'GET_RANDOM_SITE_RESET';
