export const TIMELINE_CREATE_REQUEST = 'TIMELINE_CREATE_REQUEST';
export const TIMELINE_CREATE_SUCCESS = 'TIMELINE_CREATE_SUCCESS';
export const TIMELINE_CREATE_FAIL = 'TIMELINE_CREATE_FAIL';
export const TIMELINE_CREATE_RESET = 'TIMELINE_CREATE_RESET';

export const TIMELINE_VIEW_REQUEST = 'TIMELINE_VIEW_REQUEST';
export const TIMELINE_VIEW_SUCCESS = 'TIMELINE_VIEW_SUCCESS';
export const TIMELINE_VIEW_FAIL = 'TIMELINE_VIEW_FAIL';
export const TIMELINE_VIEW_RESET = 'TIMELINE_VIEW_RESET';

export const TIMELINE_GET_REQUEST = 'TIMELINE_GET_REQUEST';
export const TIMELINE_GET_SUCCESS = 'TIMELINE_GET_SUCCESS';
export const TIMELINE_GET_FAIL = 'TIMELINE_GET_FAIL';
export const TIMELINE_GET_RESET = 'TIMELINE_GET_RESET';

export const TIMELINE_UPDATE_REQUEST = 'TIMELINE_UPDATE_REQUEST';
export const TIMELINE_UPDATE_SUCCESS = 'TIMELINE_UPDATE_SUCCESS';
export const TIMELINE_UPDATE_FAIL = 'TIMELINE_UPDATE_FAIL';
export const TIMELINE_UPDATE_RESET = 'TIMELINE_UPDATE_RESET';

export const TIMELINE_DELETE_REQUEST = 'TIMELINE_DELETE_REQUEST';
export const TIMELINE_DELETE_SUCCESS = 'TIMELINE_DELETE_SUCCESS';
export const TIMELINE_DELETE_FAIL = 'TIMELINE_DELETE_FAIL';
export const TIMELINE_DELETE_RESET = 'TIMELINE_DELETE_RESET';
